import { DndProvider} from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';
import Dnd from '../../components/Dnd/Dnd';
import DndBoard from '../../components/Dnd/DndBoard';

export default function VirtualGarden() {


    
    return (
        <DndProvider backend={HTML5Backend}>
            <h2>Simply Drag a vegetable onto the grid below to start planning your seasonal garden!  </h2>
            <div className="VirtualGarden">
                <Dnd />
                <div className="BoardGridContainer">
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                    <DndBoard />
                </div>
            </div>
            
        </DndProvider>
    );
}